/* eslint-disable import/no-cycle */
import { Cache, Model } from 'base-repo';
import {
  AllowNull, AutoIncrement, BelongsToMany, Column, NotEmpty, PrimaryKey, Table,
} from 'sequelize-typescript';
import { IUnfilledAtt, Optional } from 'utils/base-class/base.interface';

import { FacilityTest } from './FacilityTest';
import { ClinicFacility } from './ClinicFacility';

interface AutoGeneratedAttr {
  id: number;
}

interface INullableAttr extends IUnfilledAtt {
  noTelp: number;
}

export interface IModel extends
  Optional<INullableAttr>,
  AutoGeneratedAttr {
  nameClinic: string;
  addressClinic: string;
}

export type IModelCreate = Omit<IModel, 'id' | keyof AutoGeneratedAttr> & Partial<AutoGeneratedAttr>;

@Cache()
@Table({
  tableName: 'clinic',
  paranoid: true,
  indexes: [{ fields: ['is_active'] }],
})
export class Clinic extends Model<IModel, IModelCreate> implements IModel {
  @PrimaryKey
  @NotEmpty
  @AutoIncrement
  @Column
    id:number;

  @AllowNull(false)
  @Column
    nameClinic: string;

  @AllowNull(false)
  @Column
    addressClinic: string;

  @AllowNull(false)
  @Column
    noTelp: number;

  @BelongsToMany(() => FacilityTest, () => ClinicFacility)
    facilities!: Array<FacilityTest & { clinicFacility: ClinicFacility }>;
}
