/* eslint-disable import/no-cycle */
import { Cache, Model } from 'base-repo';
import {
  AllowNull, Column, Default, PrimaryKey, Scopes, Table, AutoIncrement, NotEmpty, ForeignKey,
} from 'sequelize-typescript';
import { IUnfilledAtt, Optional } from 'utils/base-class/base.interface';
import { Clinic } from './Clinic';
import { FacilityTest } from './FacilityTest';

type INullableAttr = IUnfilledAtt;

interface AutoGeneratedAttr {
  id: number;
  is_active: boolean;
}

export interface IModel extends Optional<INullableAttr>, AutoGeneratedAttr {
  clinicId: number;
  facilityTestId: number;
}

export type IModelCreate = Omit<IModel, keyof AutoGeneratedAttr> & Partial<AutoGeneratedAttr>;

@Scopes(() => ({
  active: ({
    where: {
      is_active: true,
    },
  }),
}))

@Cache()
@Table({
  tableName: 'clinic_facility',
  paranoid: true,
  indexes: [{ fields: ['is_active', 'id'], where: { is_deleted: false } }],
})

export class ClinicFacility extends Model<IModel, IModelCreate> implements IModel {
  @PrimaryKey
  @NotEmpty
  @AutoIncrement
  @Column
    id:number;

  @ForeignKey(() => Clinic)
  @AllowNull(false)
  @Column
    clinicId: number;

  @ForeignKey(() => FacilityTest)
  @AllowNull(false)
  @Column
    facilityTestId: number;

  @AllowNull(false)
  @Default(true)
  @Column
    is_active: boolean;
}
