import { Cache, Model } from 'base-repo';
import { BelongsTo, ForeignKey, Table } from 'sequelize-typescript';
import { IUnfilledAtt } from 'utils/base-class/base.interface';

import { Role } from './Role';
import { User } from './User';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface INullableAttr {
}

/**
   * auto generated attributes, cause of that removed from iModelCreate
 */
interface AutoGeneratedAttr {
  id: number;
}

export interface IModel extends Partial<IUnfilledAtt>, Partial<INullableAttr>, AutoGeneratedAttr {
  userId: number
  roleId: number
}

export type IModelCreate = Omit<IModel, keyof AutoGeneratedAttr> & Partial<AutoGeneratedAttr>;

@Cache()
@Table({
  tableName: 'user_role',
  timestamps: false,
})
export class UserRole extends Model<IModel, IModelCreate> implements IModel {
  id: number;

  @BelongsTo(() => User)
    user: User;

  @ForeignKey(() => User)
    userId: number;

  @BelongsTo(() => Role)
    role: Role;

  @ForeignKey(() => Role)
    roleId: number;
}
